lang_2_script = {
    'eng': 'eng_Latn',
    'ces': 'ces_Latn',
    'fra': 'fra_Latn',
    'deu': 'deu_Latn',
    'tur': 'tur_Latn',
    'tel': 'tel_Telu',
    'hau': 'hau_Latn',
    'amh': 'amh_Ethi',
    'mar': 'mar_Deva',
    'spa': 'spa_Latn',
    'arb': 'arb_Arab',
    'azj': 'azj_Latn',
    'kaz': 'kaz_Cyrl',
    'kir': 'kir_Cyrl',
    'uig': 'uig_Arab',
    'uzn': 'uzn_Latn',
    'ita': 'ita_Latn',
    'nld': 'nld_Latn',
    'kor': 'kor_Hang',
    'kin': 'kin_Latn',
    "pol": "pol_Latn",
    "rus": "rus_Cyrl",
    "zho": "zho_Hans",
}
